Feat: add invoke local
serverless/serverless-google-cloudfunctions pull request #258
Opened 2021-05-17 12:03 UTC by CorentinDoue

This pull request adds the implementation of the command `invoke local` for the `google` provider. It's inspired by the AWS implementation to keep the behaviors as close as possible. 

The command is available for the `nodejs` runtimes and events of type `event`

This pull request is still a draft because I want to add the support of the environment variables before merging it.

## Tests
 
[x] Units
[ ] e2e with ES5 JS
[ ] e2e with compiled JS/TS with webpack (the shortcuts of the options are not supported cf https://github.com/serverless/serverless/issues/9452)
[ ] e2e with compiled JS/TS with esbuild

## Next steps

- Add support for `http` events

2021-05-17 12:16 UTC, CorentinDoue commented
![Screenshot from 2021-05-17 14-11-21](https://user-images.githubusercontent.com/31917261/118486361-cc06df80-b719-11eb-8799-7fdb8eecd319.png)
![Screenshot from 2021-05-17 14-14-26](https://user-images.githubusercontent.com/31917261/118486825-56e7da00-b71a-11eb-88f3-d8bec48b7335.png)

The failing test is caused by an unsupported `for await` by node 8. But node 8 is no more supported since https://github.com/serverless/serverless-google-cloudfunctions/releases/tag/v4.0.0

@pgrzesik could you remove the test with node8?

2021-05-26 08:28 UTC, CorentinDoue commented
@pgrzesik can you review it?

2021-05-26 08:30 UTC, pgrzesik commented
Hello @CorentinDoue - sorry for the delay here - I'm a bit swamped with other prorities and I'm not that familiar with this plugin's codebase, but I'll try to review it as soon as possible. Thanks for your patience :bow:

2021-05-27 09:04 UTC, pgrzesik requested changes
Thanks a lot @CorentinDoue and sorry for delayed review. I'm not an expert when it comes to conventions in this repository, but overall the changes look good :+1: I only have a few minor questions/suggestions but we should be good to go soon, please let me know what do you think :bow:

2021-05-27 09:04 UTC, pgrzesik commented on provider/googleProvider.js
> +  getRuntime(funcObject) {
Good call with extracting these :+1:

2021-05-31 11:47 UTC, CorentinDoue commented on shared/utils.js
> -    this.options.runtime = _.get(this, 'options.runtime') || 'nodejs8';
I think this should have been changed in https://github.com/serverless/serverless-google-cloudfunctions/pull/244 which drop support for nodejs8. So a nodejs8 user who upgrades this package to 4.0.0 has to explicitly set runtime to `'nodejs8'`. 

So yes it's another breaking change but it is attached to the breaking change of 4.0.0

2021-05-31 11:50 UTC, CorentinDoue commented on .travis.yml
> -    - name: 'Unit Tests - Node.js v8'
ok, I'll drop the commit

2021-05-31 11:55 UTC, CorentinDoue commented on invokeLocal/googleInvokeLocal.test.js
> +        invokeLocalStub = sinon.stub(googleInvokeLocal, 'invokeLocal').returns(Promise.resolve());
done

2021-05-31 12:02 UTC, CorentinDoue commented on invokeLocal/googleInvokeLocal.test.js
> +      beforeEach(() => {
done

2021-05-31 15:41 UTC, CorentinDoue commented on invokeLocal/lib/getDataAndContext.js
> +    this.options[optionKey] = await this.serverless.utils.readFile(absolutePath);
I tried to make it as iso as possible with the AWS implementation and it loads the files with this util: https://github.com/serverless/serverless/blob/d5e2baf714958c5718610659887f485f9bd161e4/lib/plugins/aws/invokeLocal/index.js#L62

2021-05-31 15:44 UTC, CorentinDoue commented
@pgrzesik I corrected or answered your remarks. It's ready for a new review

2021-06-01 21:08 UTC, pgrzesik commented on shared/utils.js
> -    this.options.runtime = _.get(this, 'options.runtime') || 'nodejs8';
Thanks @CorentinDoue - during release of new version I'll make sure to add that to documentation for `4.0.0` release :+1:

2021-06-01 21:08 UTC, pgrzesik approved these changes
Thank you @CorentinDoue - it looks good :+1:

2021-06-01 21:08 UTC, merged